### ISSUE TITLE
One click, no confirmation option?

### ISSUE THREAD

**Issue by amandasaurus** [maripo/JOSM_easypresets#19]
I have created a preset to add a few tags to objects. There is no options, all are fixed. I have this as a button on my toolbar and it's cool!

However when I click on the button, it pops up a window asking me to apply the preset. It would great if it was possible to configure the preset to apply the tags without any user confirmation, to make it a "one click"

**Comment by maripo** [comment]
Very good suggestion! I'll implement your idea soon.
The current version automatically inserts labels to make the dialog comprehensible.
However, I understand that one-click presets are very useful (I am often annoyed when my custom "Fire hydrant manhole" preset shows a dialog before applying fixed values).

**Comment by maripo** [comment]
Creation of one-click presets is available in v1.8.1.
<img width="662" alt="presetdialog" src="https://user-images.githubusercontent.com/190194/31862857-14b5cd38-b780-11e7-8e43-cf4bfa0d079b.png">

**Comment by amandasaurus** [comment]
Awesome! I've tried 1.8.1 and that's exactly what I want! Thanks :D
