### ISSUE TITLE
error when editing an existing preset

### ISSUE THREAD

**Issue by govvin** [maripo/JOSM_easypresets#21]
I'm trying to edit an existing preset by removing a tag (in this came, the name tag) by un-setting the check box. 

However, I cannot save the edit, and the dialog box displays the message "Tag list is empty"

![image](https://user-images.githubusercontent.com/5821688/32402328-54c5b7c2-c15c-11e7-8411-9856f5aac548.png)

Work-around, is to edit the file `$HOME/.local/share/JOSM/EasyPresets.xml` in an external editor

**Comment by maripo** [comment]
Thank you, this problem was reproduced in my environment.

**Comment by maripo** [comment]
This bug was fixed in v1.9.1.
