### ISSUE TITLE
unexpected behavior, manage custom preset dialog

### ISSUE THREAD

**Issue by govvin** [maripo/JOSM_easypresets#22]
When editing existing presets in the dialog box, the man dialog box should not disappear after you exit editing, so you can continue to edit more, if you wish to do so.

Currently, after closing the editor, the custom preset dialog box also disappears.

**Comment by maripo** [comment]
Your suggestion is quite right! I've implemented it in v1.9.2. Now users can edit multiple presets more pleasantly.
