### ISSUE TITLE
duplicate presets found under Custom Presets

### ISSUE THREAD

**Issue by govvin** [maripo/JOSM_easypresets#24]
During a JOSM session, the list of presets found under Custom Presets menu keeps duplicating everytime I add a new one, or edit an existing preset.  This reverts to normal after a reboot of JOSM. I'm running version 13053.

![image](https://user-images.githubusercontent.com/5821688/32412687-958ee07e-c23a-11e7-9882-ff8713807bc0.png)

**Comment by maripo** [comment]
Fixed in v1.9.3. Thank you for your report.
