### ISSUE TITLE
Update to latest JOSM

### ISSUE THREAD

**Issue by don-vip** [maripo/JOSM_easypresets#28]
We have removed a lot of deprecated API as advertised on the mailing list, see https://josm.openstreetmap.de/ticket/15310

As a result this plugin is no longer compatible, can you please update it?

Thanks.

**Comment by maripo** [comment]
Sorry, the version tag in build.xml was wrong (because I copied it from previously developed plugin). It is compatible with current stable version, v13170. 
I haven't tested it with dev versions. I'll support the latest dev version by the time it's released for common users.

**Comment by don-vip** [comment]
This is not how JOSM works. Nightly versions are used everyday by hundreds of users and you must be compatible, please don't wait for the stable version to be released. That's exactly why there is the Main-Version attribute in manifest, so that you can publish a version requiring a recent JOSM version without disturbing users still using the stable version. Concerning plugin updates, it's the other way around: by the end of the month, I will remove from our default list the rare plugins (if any) still not compatible with latest version. You can check your compatibility status by looking at our [Jenkins job ](https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/warnings3). It is run every 6 hours and currently lists 4 plugins.

**Comment by maripo** [comment]
OK, I understand.

**Comment by maripo** [comment]
I replaced deprecated classes and methods with new ones and confirmed that compatibility errors occur in build 13180.
https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/911/warnings3Result/

**Comment by don-vip** [comment]
Issues are gone now, thanks a lot!
