### ISSUE TITLE
What is "hoge"?

### ISSUE THREAD

**Issue by govvin** [maripo/JOSM_easypresets#31]
![image](https://user-images.githubusercontent.com/5821688/35134814-be93113e-fd13-11e7-8ae3-bd62bcb8e653.png)

When creating a textbox type field, the default text suggested is "hoge"? Perhaps, the suggested value could be the key instead? (like "name", for example)

**Comment by maripo** [comment]
Thank you for your report. This problem was contained in older versions. I've updated the plugin to make sure now. Please tell me if the problem happens again. The latest release is v1.14.4.

**Comment by govvin** [comment]
This is no longer an issue in the latest release, v1.14.4 Thank you for the update.
