### ISSUE TITLE
Update to JOSM 13564

### ISSUE THREAD

**Issue by don-vip** [maripo/JOSM_easypresets#33]
Hello,
I made a breaking change in https://josm.openstreetmap.de/changeset/13564/josm/#file26
The method `TaggingPresetType.forPrimitive` now takes an `IPrimitive` parameter instead of an `OsmPrimitive`.
Your plugin is impacted (`CreatePresetAction:55`), see https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/1372/warnings3Result/

**Comment by stoecker** [comment]
Beep. Reminder.

**Comment by maripo** [comment]
Thank you, I remember it. I need some days to start it because of mental fatigue from business and private issues:-(

**Comment by maripo** [comment]
Fixed in v1.12
https://github.com/maripo/JOSM_easypresets/releases/tag/v1.12

**Comment by don-vip** [comment]
I confirm it's working, we can close this issue :)
