### ISSUE TITLE
plugin cannot create presets on JOSM v13576

### ISSUE THREAD

**Issue by govvin** [maripo/JOSM_easypresets#34]
After my upgrade to current version of JOSM, I can no longer create presets.

I can still manage and edit existing presets but unable to create new ones. There are no error alerts whenever I attempt to create a new preset.

**Comment by don-vip** [comment]
We received a new bugreport on JOSM tracker, I don't know if it is the same issue: https://josm.openstreetmap.de/ticket/16377

**Comment by govvin** [comment]
It looks like the same issue @don-vip .

Additional information:
While there are no error messages when trying to create presets, I found one while trying to find a workaround,  when you attempt to copy/clone an existing preset.

![image](https://user-images.githubusercontent.com/5821688/41410228-59e8436a-700b-11e8-90a2-217a0701b117.png)

The following is the crash data error:
[josm_easy_preset_crash_data.txt](https://github.com/maripo/JOSM_easypresets/files/2109542/josm_easy_preset_crash_data.txt)

**Comment by maripo** [comment]
Thank you for reporting. I couldn't reproduce it on my environment (macOS High Sierra 10.13.4 + JOSM 13878). Can you please give me detailed information about your environment?

This user reported the same problem from Windows 7. It may be OS dependent.
https://josm.openstreetmap.de/ticket/16377

**Comment by govvin** [comment]
Hi @maripo . I'm on Ubuntu. Attached is the debug text
[create_presets_debug_info.txt](https://github.com/maripo/JOSM_easypresets/files/2104399/create_presets_error.txt)

**Comment by maripo** [comment]
Thanks, it's a clue to solution.

**Comment by maripo** [comment]
Another report on Twitter
https://twitter.com/hide19710605/status/1007946924844986369

**Comment by maripo** [comment]
Fixed in v1.13. Current source code did not contain this defect but the  jar file distributed as v1.12 was wrong one. Sorry for inconvenience.

**Comment by govvin** [comment]
This works! Thank you for the fix, @maripo
