### ISSUE TITLE
Icons are too big!

### ISSUE THREAD

**Issue by maripo** [maripo/JOSM_easypresets#35]
<img width="694" alt="screen shot 2018-06-17 at 23 44 47" src="https://user-images.githubusercontent.com/190194/41509040-84bcf728-7288-11e8-8191-58ea58d4d0a5.png">

**Comment by maripo** [comment]
upButton = new JButton();
			upButton.setIcon(ImageProvider.get("dialogs", "up"));
			downButton = new JButton();
			downButton.setIcon(ImageProvider.get("dialogs", "down"));

**Comment by don-vip** [comment]
That's the SVG effect, we fixed the same bugs in core :) https://josm.openstreetmap.de/ticket/16358

**Comment by maripo** [comment]
Thank you, I just fixed it in v1.13.2 by specifying icon size explicitly.
