### ISSUE TITLE
pr46 : F3(プリセット検索)

### ISSUE THREAD

**Issue by yuuhayashi** [maripo/JOSM_easypresets#47]
# Issue F3(プリセット検索)

- EasyPresetsがJOSMメニューの「プリセット検索 F3」にヒットしない

- EasyPresets.xmlのロード時に、TaggingPresets.addTaggingPresets(presetList);を行うと「プリセット検索 F3」にヒットするようになる

  そうすると、別の問題が発生する

*** Exportしたカスタムプリセットファイルを JOSMに「プリセット登録」すると、

*** EasyPresetの「カスタムプリセット」が表示されなくなる

# Issue ツールバーにEasyPresetsのプリセットが登録できない

* JOSMの設定でEasyPresetsのカスタムメニュー項目を「ツーバー」に設定することができない
* EasyPresets.xmlのロード時に、TaggingPresets.addTaggingPresets(presetList);を行うと「ツーバー登録設定画面に表示されるようになる」
** EasyPresetsのグループはツールバーに登録できない
** EasyPresetsの個別プリセットをツールバーに登録できる
*** ツールバーに登録したプリセットを「カスタムプリセット編集」で更新すると、ツールバーのプリセットが動作しなくなる。
**** JOSM再起動で復活する
***  ツールバーに登録したプリセットを「カスタムプリセット編集」で削除すると、ツールバーのプリセットが動作しなくなる
**** JOSM再起動しても回復しない

上記２件の問題はどちらも TaggingPresets.addTaggingPresets(presetList) をJOSMの起動時以外に行うことに起因しているようです。

TaggingPresets.addTaggingPresets(presetList)による TaggingPresets.taggingPresets への登録は、静的なインスタンスのみの登録で、登録された内容が変更することは想定されていないようです。

EasyPresetsの利用方法として、

 (1) 編集した「カスタムプリセット」を「エクスポート」して、

 (2) エクスポートしたファイルを適宜<group>を挿入するなどして変更する

 (３)エクスポートしたファイルをJOSMにプリセット登録する

という利用法が想定されます。

「グループ階層化」を実装した場合は、(2)に手順が不要になる。

## エクスポートしたファイルをJOSMのプリセットに登録した場合、

登録したプリセットのpath+name とEasyPresetsのプリセットの path+name が重複してしまい、いろいろな不具合が発生します。（冒頭に示した問題点）

## 解決策

(1) EasyPresetsの管理対象プリセットは TaggingPresets.taggingPresets に登録しない

- エクスポート → JOSMプリセット登録 することによって、
 - 「プリセット検索 F3」にヒットするようになる
 - JOSMツールバーに登録することもできる

(2) EasyPresets.xml のXML構造を変更する

- エクスポート → JOSMプリセット登録 によって、プリセット名のパス名が重複しないようにする対策です
 - root<prisets>の下に単一の<group name="Custom Prisets">を置き、すべてのプリセットを此のタグに入れる
 - エクスポート時に、「プリセット名称」を入力してもらい、エクスポートファイルは<group name="＜プリセット名称＞">としてEasyPresets.xmlのプリセットと区別できるようにする
  - 「プリセット名称」には「Custom Presets」を指定できないようにする
 - 現versionのEasyPresetsで作成されたEasyPresets.xmlをリードしたときに、新バージョンのEasyPresets.xmlフォーマットに自動変換する

とりあえずこの２点の対策から手を付けていきます。

**Comment by yuuhayashi** [comment]
-

**Comment by maripo** [comment]
ありがとうございます。以前はロードのタイミングもデータ構造も一般プリセットと一緒だったので問題なかったのですが、リロード & グループ機能でいろいろ対応が必要なようですね。よろしくおねがいします。
