### ISSUE TITLE
EasyPresets are no longer searchable from Search Presets

### ISSUE THREAD

**Issue by govvin** [maripo/JOSM_easypresets#56]
I'm using EasyPresets v160504256 in JOSM v17428 and a few days ago EasyPresets entries stopped being searchable from Search Presets (activate using function key F3)

![image](https://user-images.githubusercontent.com/5821688/104791887-3ee96380-57d7-11eb-95fc-631d82b4c47d.png)

Before, it was possible to search for EasyPreset entries
![image](https://user-images.githubusercontent.com/5821688/104792478-88d34900-57d9-11eb-8d27-1fa0a5e4404d.png)

This used to be a very convenient way of using the presets, especially when you have a very long list of entries.
![image](https://user-images.githubusercontent.com/5821688/104791951-94257500-57d7-11eb-9cde-87801d178d94.png)

**Comment by govvin** [comment]
This is still the behaviour on v1616852928. Custom presets are not searchable.

**Comment by maripo** [comment]
Fixed in release v2.4. Can you test it?

**Comment by govvin** [comment]
I just tested v2.4, and search is working again. Thank you, @maripo.

**Comment by yuuhayashi** [comment]
v2.4 conflicts with exported files(named "カスタムプリセット").
