### ISSUE TITLE
Strange labels in Preset Editor dialog

### ISSUE THREAD

**Issue by pgavrilov** [maripo/JOSM_easypresets#61]
1) Strange label "PresetEditorDialogreset" in left top corner.
2) Label "Show the name of the dialog" instead simple "Show dialog on apply" - as this option really works.
EasyPreset v1623509627, JOSM v18193.

![JOSM Easy Preset strange labels](https://user-images.githubusercontent.com/3817702/132138494-2b011355-3de8-4333-89e8-2007eb610b43.jpg)

**Comment by maripo** [comment]
It's fixed in v2.5.1 release. Thank you for reporting!
https://github.com/maripo/JOSM_easypresets/releases/tag/v2.5.1
